### ISSUE TITLE
Style Register and Login Form

### ISSUE THREAD

**Issue by divy-03** [divy-03/DreamLeague#2]
Try to style the login and sign up form using SCSS.  If possible add Images and SVG's and onClick animations to swap from login to register form

**Comment by hUnteRrooTs** [comment]
Can I style the **login page** ???

**Comment by divy-03** [comment]
Sure! It would be a great help. @TheUser5050

**Comment by hUnteRrooTs** [comment]
Thank U man

**Comment by hUnteRrooTs** [comment]
Can I use **_tailwindCSS_** ??

**Comment by divy-03** [comment]
It's up to you. But I recommend using Sass.

**Comment by hUnteRrooTs** [comment]
I will use **_TailwindCSS_**. Because I know it well. In **_SCSS_** it is also like CSS but it's like a pain to me.

**Comment by divy-03** [comment]
Thanks a lot, @TheUser5050! The login form looks great with the new Tailwind CSS styling and React Hook Form integration. Everything's working smoothly. Appreciate your work on this! Closing the issue now.
Looking forward to more great contributions from you in the future!

**Comment by hUnteRrooTs** [comment]
What exactly this website will do??

**Comment by divy-03** [comment]
"At our college, we frequently organize futsal or football tournaments where students form 6 or 11-player teams. Currently, teams are often created based on friendship, leading to imbalances. To address this, I want to develop a website where:

* Students register and are rated by administrators based on their skills and performance (1-5 stars).
* Approximately 10-12 captains are selected and provided with a small amount of virtual currency.
* Players are auctioned, with captains bidding to form their teams.
* Captains must balance their budget to acquire players of various skill levels.
* Post-auction, the website will display team rosters, player statistics, team standings, and individual rankings."

**Comment by hUnteRrooTs** [comment]
Hey do you know NextJS

**Comment by divy-03** [comment]
Not yet, but I really want to learn it after I master MERN stack.

**Comment by hUnteRrooTs** [comment]
Need any help in the project??

**Comment by divy-03** [comment]
I'm buried in college assignments. I'll raise up issues when I've got some free time.

**Comment by hUnteRrooTs** [comment]
K
